openapi: 3.0.0
info:
  title: Tracking learning progress
  description: This is a MERN based school project, a Learning Progress Tracker app's API documentation.
  version: 0.1.0
  contact:
    email: "bolyaicsaba@gmail.com"

servers:
  - url: http://localhost:8000/api

tags:
- name: "test"
  description: "Test endpoint"
- name: "lessons"
  description: "What you can do with lessons"
- name: "quotes"
  description: "Access to motivational quotes"
- name: "user"
  description: "Operations about user, including the lesson statuses, nicknames, preferred quotes"

paths:
  /test:
    get:
      tags:
      - "test"
      summary: Test endpoint to test that the server is on.
      description: ""
      responses:
        "200":    # status code
          description: "successful test, a json with a message"
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: "Express generator server is on"
        "500":  # status code
          $ref: "#/components/responses/ServerError"

  /lessons:
    get:
      tags:
      - "lessons"
      summary: Get the lessons of a course.
      description: In this moment you can get only the lessons of the basic course, but in never versions, you can choose between the courses
      responses:
        "200":    # status code
          description: "successful operation, an array with the classes"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Lesson"
        "404":  # status code
          description: "no lessons found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No lessons found."
        "500":  # status code
          $ref: "#/components/responses/ServerError"
  
  /fillCourses:
    get:
      tags:
      - "lessons"
      summary: Fills the Courses collection from a file
      description: Fills the Courses collection with the json from the ./Data/Courses/foundation.json file
      responses:
        "200":  # status code
          description: "successful operation, a message: 'Courses set!'"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Lesson"
        "500":  # status code
          $ref: "#/components/responses/ServerError"

  /quotes:
    get:
      tags:
      - "quotes"
      summary: Get a motivational quote from the collection
      description: The quote you get is randomly generated from the database, later will be based on the user's preferences
      responses:
        "200":    # status code
          description: "successful operation, an object with a number and a string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quote"
        "404":  # status code
          description: "no quotes found"
        "500":  # status code
          $ref: "#/components/responses/ServerError"
          
  /fillQuotes:
    get:
      tags:
      - "quotes"
      summary: Fills the Quotes collection from a file
      description: Fills the Quotes collection with the json from the ./DataQuotes/quotes.json file
      responses:
        "200":  # status code
          description: "successful operation, a message: 'Quotes set!'"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Quote"
        "404":  # status code
          description: "no quotes found"
        "500":  # status code
          $ref: "#/components/responses/ServerError"


  /login:
    post:
      tags:
      - "user"
      summary: Google login endpoint
      description: Sends the code to the google and saves the user data sent from the google and creates a jwt signed token and sends it back to frontend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Google auth code
      responses:
        "200":    # status code
          description: "successful operation, a jwt token with the user information"
          content:
            application/json:
              schema:
                type: string
        "401":  # status code
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Code missing"
        "500":  # status code
          $ref: "#/components/responses/ServerError"

  /progress:
    post:
      tags:
      - "user"
      summary: Get the class progress of an user
      description: The classes are build of lessons, and the number of lessons is equal with the number of progress array element
      requestBody:
        description: The e-mail adress of the user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "barney@stinson.cool"
      responses:
        "200":    # status code
          description: "successful operation, an array with the user's progress in the lesson"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Google_User"
        "404":  # status code
          description: "e-mail is missing"
        "500":  # status code
          $ref: "#/components/responses/ServerError"
  
  /setprogress:
    post:
      tags:
      - "user"
      summary: Set the class progress of an user
      description: As the user progresses with learning, updates his/her class status
      requestBody:
        description: The e-mail adress of the user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "barney@stinson.cool"
                progress:
                  type: array
                  items:
                    type: string
                  example: ["Done", "Act", "Next"]
      responses:
        "200":    # status code
          description: "successful operation, the user progress array is updated"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Google_User"
        "404":  # status code
          description: "e-mail is missing or progress array is missing"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "email is missing"
        "500":  # status code
          $ref: "#/components/responses/ServerError"
          
  /deleteuser:
    delete:
      tags:
      - "user"
      summary: Delete the User
      description: ""
      responses:
        "200":  # status code
          description: "User deleted"
          content:
            application/json:
              schema:
                type: string
        "404":  # status code
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "user not existing"
        "500":  # status code
          $ref: "#/components/responses/ServerError"

            
components:
  schemas:
    Lesson:
      type: "object"
      required:
      - "lessons"
      properties:
        title:
          type: "string"
        lessons:
          type: "array"
          items:
            type: "string"
    Quote:
      type: "object"
      required:
      - "quote"
      properties:
        nr:
          type: "integer"
          format: "int32"
        quote:
          type: "string"
    Google_User:
      type: "object"
      required:
      - "google_id"
      - "full_name"
      - "email"
      - "picture"
      - "date"
      properties:
        google_id:
          type: "string"
        full_name:
          type: "string"
        email:
          type: "string"
        picture:
          type: "string"
        date:
          type: "string"
        given_name:
          type: "string"
        nick_name:
          type: "integer"
          default: "*"
        level:
          type: "integer"
          format: "int32"
        courses:
          type: object
    Foundations:
      type: "object"
      properties:
        foundations:
          type: "array"
          default: [
            "Act",
            "Next",
            "Next",
            "Next",
            "Next",
            "Next",
            "Next",
            "Next",
            "Next",
            "Next",
          ]
          items:
            type: "string"
      xml:
        name: "User"
        
  responses:
    ServerError:
      description: Server error
      content:
        text/html:
          schema: 
            type: "string"
            example: error